// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEBue74YcN9b4CuiXZ7QZk4Kk9UzJjMYE',
    appId: '1:375020778229:web:d75aec23a6d960b524cbbc',
    messagingSenderId: '375020778229',
    projectId: 'clube-vinho-app',
    authDomain: 'clube-vinho-app.firebaseapp.com',
    storageBucket: 'clube-vinho-app.firebasestorage.app',
    measurementId: 'G-3N9ZZKVQZQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVDEeZqoVCzyRkT-BbIVQvk1A5b0NDXbg',
    appId: '1:375020778229:android:57d1edd121c96ce324cbbc',
    messagingSenderId: '375020778229',
    projectId: 'clube-vinho-app',
    storageBucket: 'clube-vinho-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGGmEwTjzwsngu3kMj4fWm_yhIU82dURs',
    appId: '1:375020778229:ios:905cd06d2c6bc79c24cbbc',
    messagingSenderId: '375020778229',
    projectId: 'clube-vinho-app',
    storageBucket: 'clube-vinho-app.firebasestorage.app',
    iosBundleId: 'com.example.appWebView',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGGmEwTjzwsngu3kMj4fWm_yhIU82dURs',
    appId: '1:375020778229:ios:905cd06d2c6bc79c24cbbc',
    messagingSenderId: '375020778229',
    projectId: 'clube-vinho-app',
    storageBucket: 'clube-vinho-app.firebasestorage.app',
    iosBundleId: 'com.example.appWebView',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEBue74YcN9b4CuiXZ7QZk4Kk9UzJjMYE',
    appId: '1:375020778229:web:1d1ebd564219aa5c24cbbc',
    messagingSenderId: '375020778229',
    projectId: 'clube-vinho-app',
    authDomain: 'clube-vinho-app.firebaseapp.com',
    storageBucket: 'clube-vinho-app.firebasestorage.app',
    measurementId: 'G-4ELTP6BM5B',
  );
}
